export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_REDIRECT_PATH = "SET_REDIRECT_PATH";
export const SET_PAGE_TITLE = "SET_PAGE_TITLE";
export const PBX_LOADING_START = "PBX_LOADING_START";
export const PBX_LOADING_FINISH = "PBX_LOADING_FINISH";






